name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install package with [ci] extras
        run: |
          python -m pip install --upgrade pip
          pip install -e .[ci]

      - name: Lint with flake8
        run: flake8 dynamic_config_manager tests
        continue-on-error: true

      - name: Run tests with pytest
        run: pytest -q
